/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.49
 * Generated at: 2025-12-08 06:57:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.meet;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.*;
import dto.MeetingDTO;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("dto.MeetingDTO");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>동네 모임</title>\n");
      out.write("\n");
      out.write("    <!-- 메인 스타일 가져오기 -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/resources/css/home.css\">\n");
      out.write("\n");
      out.write("    <style>\n");
      out.write("        body {\n");
      out.write("            background: #F5F6FA;\n");
      out.write("            font-family: 'Pretendard';\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .page-wrapper {\n");
      out.write("            width: 1400px;\n");
      out.write("            margin: 0 auto;\n");
      out.write("            padding: 20px 0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .layout {\n");
      out.write("            display: flex;\n");
      out.write("            gap: 30px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* ---------- 좌측 사이드바 ---------- */\n");
      out.write("        .sidebar {\n");
      out.write("            width: 260px;\n");
      out.write("            background: white;\n");
      out.write("            padding: 25px 20px;\n");
      out.write("            border-radius: 24px;\n");
      out.write("            box-shadow: 0 6px 20px rgba(0,0,0,0.06);\n");
      out.write("            height: auto;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .side-title {\n");
      out.write("            font-size: 18px;\n");
      out.write("            font-weight: 700;\n");
      out.write("            margin-bottom: 12px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .filter-group {\n");
      out.write("            margin-bottom: 28px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .filter-group ul li {\n");
      out.write("            list-style: none;\n");
      out.write("            margin: 8px 0;\n");
      out.write("            cursor: pointer;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* ---------- 우측 콘텐츠 ---------- */\n");
      out.write("        .content {\n");
      out.write("            flex: 1;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .content-header {\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: space-between;\n");
      out.write("            align-items: center;\n");
      out.write("            margin-bottom: 25px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .search-box input {\n");
      out.write("            width: 350px;\n");
      out.write("            height: 42px;\n");
      out.write("            padding: 0 15px;\n");
      out.write("            border-radius: 12px;\n");
      out.write("            border: 1px solid #ccc;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .write-btn {\n");
      out.write("            background: #FF7C40;\n");
      out.write("            color: white;\n");
      out.write("            padding: 10px 18px;\n");
      out.write("            border-radius: 12px;\n");
      out.write("            font-size: 14px;\n");
      out.write("            font-weight: 700;\n");
      out.write("            text-decoration: none;\n");
      out.write("            transition: 0.2s;\n");
      out.write("        }\n");
      out.write("        .write-btn:hover {\n");
      out.write("            background: #e46d33;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* ---------- 모임 리스트 카드 ---------- */\n");
      out.write("        .meeting-card {\n");
      out.write("            background: white;\n");
      out.write("            padding: 22px 25px;\n");
      out.write("            margin-bottom: 18px;\n");
      out.write("            border-radius: 20px;\n");
      out.write("            box-shadow: 0 4px 16px rgba(0,0,0,0.07);\n");
      out.write("            cursor: pointer;\n");
      out.write("            transition: 0.2s;\n");
      out.write("        }\n");
      out.write("        .meeting-card:hover {\n");
      out.write("            transform: translateY(-4px);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .meeting-title {\n");
      out.write("            font-size: 18px;\n");
      out.write("            font-weight: 700;\n");
      out.write("            margin-bottom: 6px;\n");
      out.write("        }\n");
      out.write("        .meeting-content {\n");
      out.write("            font-size: 14px;\n");
      out.write("            color: #666;\n");
      out.write("            margin-bottom: 10px;\n");
      out.write("        }\n");
      out.write("        .meeting-meta {\n");
      out.write("            font-size: 12px;\n");
      out.write("            color: #888;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .status-btn {\n");
      out.write("            float: right;\n");
      out.write("            font-size: 13px;\n");
      out.write("            padding: 5px 12px;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            color: white;\n");
      out.write("            background: #FF7C40;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<div class=\"page-wrapper\">\n");
      out.write("\n");
      out.write("    <!-- 공통 헤더 -->\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/include/header.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("    <div class=\"layout\">\n");
      out.write("\n");
      out.write("        <!-- ---------- 좌측 필터 사이드바 ---------- -->\n");
      out.write("        <div class=\"sidebar\">\n");
      out.write("            <div class=\"filter-group\">\n");
      out.write("                <div class=\"side-title\">카테고리</div>\n");
      out.write("                <ul>\n");
      out.write("                    <li>전체</li>\n");
      out.write("                    <li>산책</li>\n");
      out.write("                    <li>헬스</li>\n");
      out.write("                    <li>애견</li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"filter-group\">\n");
      out.write("                <div class=\"side-title\">모임 인원</div>\n");
      out.write("                <ul>\n");
      out.write("                    <li>1명 이상</li>\n");
      out.write("                    <li>최대 10명</li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"filter-group\">\n");
      out.write("                <div class=\"side-title\">필터</div>\n");
      out.write("                <input type=\"date\" style=\"width:100%; padding:8px; border-radius:12px; border:1px solid #ddd;\">\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- ---------- 우측 콘텐츠 ---------- -->\n");
      out.write("        <div class=\"content\">\n");
      out.write("\n");
      out.write("            <div class=\"content-header\">\n");
      out.write("                <!-- 검색 -->\n");
      out.write("                <div class=\"search-box\">\n");
      out.write("                    <input type=\"text\" placeholder=\"Search Product Here\">\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <!-- 모임 생성 버튼 -->\n");
      out.write("                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/views/meet/meetForm.jsp\" class=\"write-btn\">모임 생성 ✏️</a>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!-- ====== 모임 리스트 출력 ====== -->\n");
      out.write("            ");

                List<MeetingDTO> list = (List<MeetingDTO>) request.getAttribute("meetingList");
                if (list == null || list.isEmpty()) {
            
      out.write("\n");
      out.write("                <p style=\"color:#555; font-size:16px;\">등록된 모임이 없습니다.</p>\n");
      out.write("\n");
      out.write("            ");
 } else {
                   for (MeetingDTO m : list) { 
      out.write("\n");
      out.write("\n");
      out.write("            <div class=\"meeting-card\"\n");
      out.write("                 onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/meeting/info?meetingId=");
      out.print( m.getMeetingId() );
      out.write("'\">\n");
      out.write("\n");
      out.write("                <div class=\"meeting-title\">");
      out.print( m.getTitle() );
      out.write("</div>\n");
      out.write("                <div class=\"meeting-content\">");
      out.print( m.getContent() );
      out.write("</div>\n");
      out.write("\n");
      out.write("                <div class=\"meeting-meta\">\n");
      out.write("                    ");
      out.print( m.getDate() );
      out.write("\n");
      out.write("                    <span class=\"status-btn\">모집인원</span>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            ");
 } } 
      out.write("\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
