/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.49
 * Generated at: 2025-12-08 06:57:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.meet;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import dto.UserAddressDTO;

public final class meetForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("dto.UserAddressDTO");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>모임 생성</title>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("    body { font-family: Arial, sans-serif; background: #f5f6fa; padding: 0; margin: 0; }\n");
      out.write("    .container {\n");
      out.write("        width: 650px; max-width: 95%; background: #fff; margin: 40px auto;\n");
      out.write("        padding: 30px; border-radius: 15px; box-shadow: 0 6px 20px rgba(0,0,0,0.1);\n");
      out.write("    }\n");
      out.write("    h2 { text-align: center; color: #FF7C40; }\n");
      out.write("    form { display: flex; flex-direction: column; gap: 15px; }\n");
      out.write("    input, textarea, select { padding: 10px; border-radius: 8px; border: 1px solid #ddd; width: 100%; box-sizing: border-box; }\n");
      out.write("    textarea { resize: vertical; min-height: 70px; }\n");
      out.write("    button { background: #FF7C40; border: none; padding: 12px; border-radius: 10px; color: #fff; font-weight: bold; cursor: pointer; }\n");
      out.write("\n");
      out.write("    /* 메인 이미지 */\n");
      out.write("    #mainImagePreview {\n");
      out.write("        width: 100%; height: 250px; object-fit: cover;\n");
      out.write("        border: 2px solid #ddd; border-radius: 10px; margin-bottom: 10px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    /* 5칸 썸네일 박스 */\n");
      out.write("    #thumbnailGrid {\n");
      out.write("        display: grid;\n");
      out.write("        grid-template-columns: repeat(5, 1fr);\n");
      out.write("        gap: 10px;\n");
      out.write("    }\n");
      out.write("    .thumb-box {\n");
      out.write("        width: 100%; padding-top: 100%; position: relative;\n");
      out.write("        border: 2px dashed #ccc; border-radius: 10px;\n");
      out.write("        display: flex; justify-content: center; align-items: center;\n");
      out.write("        font-size: 12px; color: #aaa;\n");
      out.write("        overflow: hidden;\n");
      out.write("    }\n");
      out.write("    .thumb-box img {\n");
      out.write("        position: absolute; top: 0; left: 0; width: 100%; height: 100%;\n");
      out.write("        object-fit: cover; cursor: pointer;\n");
      out.write("    }\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("    let imageList = []; // 업로드한 이미지 파일들을 저장하는 배열(최대 5개)\n");
      out.write("    const POPUP_KEY = \"");
      out.print( "devU01TX0FVVEgyMDI1MTEyNDEwMTMwNjExNjQ4NTc=" );
      out.write("\";\n");
      out.write("    const RETURN_URL = \"http://localhost:8080");
      out.print( request.getContextPath() );
      out.write("/views/util/addressPopupReturn.jsp\";\n");
      out.write("\n");
      out.write("    // 주소 검색 팝업\n");
      out.write("    function openJusoPopup() {\n");
      out.write("        window.open(\n");
      out.write("            \"https://business.juso.go.kr/addrlink/addrLinkUrl.do?confmKey=\" + POPUP_KEY \n");
      out.write("            + \"&returnUrl=\" + encodeURIComponent(RETURN_URL)\n");
      out.write("            + \"&resultType=4\",\n");
      out.write("            \"jusoPopup\",\n");
      out.write("            \"width=570,height=420,scrollbars=yes,resizable=yes\"\n");
      out.write("        );\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    // 이미지 추가\n");
      out.write("    function addImages(event) {\n");
      out.write("        const files = Array.from(event.target.files);\n");
      out.write("        files.forEach(file => {\n");
      out.write("            if (imageList.length >= 5) return;  \n");
      out.write("            imageList.push(file);\n");
      out.write("        });\n");
      out.write("        renderThumbnails();\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    // 썸네일 + 메인 이미지 갱신\n");
      out.write("    function renderThumbnails() {\n");
      out.write("        const grid = document.getElementById(\"thumbnailGrid\");\n");
      out.write("        const mainPreview = document.getElementById(\"mainImagePreview\");\n");
      out.write("        grid.innerHTML = \"\";\n");
      out.write("\n");
      out.write("        if (imageList.length > 0) {\n");
      out.write("            mainPreview.src = URL.createObjectURL(imageList[0]);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        for (let i = 0; i < 5; i++) {\n");
      out.write("            const box = document.createElement(\"div\");\n");
      out.write("            box.classList.add(\"thumb-box\");\n");
      out.write("\n");
      out.write("            if (imageList[i]) {\n");
      out.write("                const img = document.createElement(\"img\");\n");
      out.write("                img.src = URL.createObjectURL(imageList[i]);\n");
      out.write("                img.onclick = () => mainPreview.src = img.src;\n");
      out.write("                box.appendChild(img);\n");
      out.write("            } else {\n");
      out.write("                box.innerText = \"이미지 없음\";\n");
      out.write("            }\n");
      out.write("            grid.appendChild(box);\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    // form submit 전에 좌표 가져오기\n");
      out.write("    function submitFormWithCoordinates(form) {\n");
      out.write("        const geocoder = new kakao.maps.services.Geocoder();\n");
      out.write("        const roadAddr = document.getElementById(\"roadAddressValue\").value;\n");
      out.write("        const jibunAddr = document.getElementById(\"jibunAddressValue\").value;\n");
      out.write("        const finalAddress = roadAddr || jibunAddr;\n");
      out.write("\n");
      out.write("        if (!finalAddress) {\n");
      out.write("            alert(\"주소가 없습니다. 주소 검색을 먼저 해주세요.\");\n");
      out.write("            return false;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        // 좌표 검색 후 submit\n");
      out.write("        geocoder.addressSearch(finalAddress, function(result, status) {\n");
      out.write("            if (status === kakao.maps.services.Status.OK) {\n");
      out.write("                document.getElementById(\"latitude\").value = result[0].y;\n");
      out.write("                document.getElementById(\"longitude\").value = result[0].x;\n");
      out.write("                form.submit(); // 서버로 전송\n");
      out.write("            } else {\n");
      out.write("                alert(\"주소 → 좌표 변환 실패: \" + status);\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        return false; // form 기본 submit 막음, 좌표 완료 후 submit\n");
      out.write("    }\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<script src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=ef8233e9a835b606aa5918095ec92f2b&libraries=services\"></script>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("<div class=\"container\">\n");
      out.write("    <h2>모임 생성</h2>\n");
      out.write("\n");
      out.write("    <form id=\"insertForm\" action=\"");
      out.print( request.getContextPath() );
      out.write("/meeting/insert\"\n");
      out.write("          method=\"post\" enctype=\"multipart/form-data\"\n");
      out.write("          onsubmit=\"return submitFormWithCoordinates(this);\">\n");
      out.write("\n");
      out.write("        <!-- 대표 이미지 -->\n");
      out.write("        <img id=\"mainImagePreview\" src=\"#\" alt=\"메인 이미지\">\n");
      out.write("\n");
      out.write("        <!-- 5칸 썸네일 -->\n");
      out.write("        <div id=\"thumbnailGrid\"></div>\n");
      out.write("\n");
      out.write("        <!-- 이미지 업로드 input -->\n");
      out.write("        <label>이미지 업로드 (최대 5장)</label>\n");
      out.write("        <input type=\"file\" accept=\"image/*\" name = \"images\" multiple onchange=\"addImages(event)\">\n");
      out.write("\n");
      out.write("        <!-- 주소 검색 -->\n");
      out.write("        <label>주소</label>\n");
      out.write("        <button type=\"button\" onclick=\"openJusoPopup()\">주소 검색</button>\n");
      out.write("\n");
      out.write("        <label>도로명주소</label>\n");
      out.write("        <input type=\"text\" id=\"roadAddress\" disabled\n");
      out.write("             value=\"");
      out.print( (session.getAttribute("addressInfo") != null 
                 && ((UserAddressDTO)session.getAttribute("addressInfo")).getRoadAddress() != null) 
                 ? ((UserAddressDTO)session.getAttribute("addressInfo")).getRoadAddress() : "" );
      out.write("\">\n");
      out.write("        <input type=\"hidden\" id=\"roadAddressValue\" name=\"roadAddress\"\n");
      out.write("             value=\"");
      out.print( (session.getAttribute("addressInfo") != null 
                 && ((UserAddressDTO)session.getAttribute("addressInfo")).getRoadAddress() != null) 
                 ? ((UserAddressDTO)session.getAttribute("addressInfo")).getRoadAddress() : "" );
      out.write("\">\n");
      out.write("\n");
      out.write("        <label>지번주소</label>\n");
      out.write("        <input type=\"text\" id=\"jibunAddress\" disabled\n");
      out.write("             value=\"");
      out.print( (session.getAttribute("addressInfo") != null 
                 && ((UserAddressDTO)session.getAttribute("addressInfo")).getJibunAddress() != null) 
                 ? ((UserAddressDTO)session.getAttribute("addressInfo")).getJibunAddress() : "" );
      out.write("\">\n");
      out.write("        <input type=\"hidden\" id=\"jibunAddressValue\" name=\"jibunAddress\"\n");
      out.write("             value=\"");
      out.print( (session.getAttribute("addressInfo") != null 
                 && ((UserAddressDTO)session.getAttribute("addressInfo")).getJibunAddress() != null) 
                 ? ((UserAddressDTO)session.getAttribute("addressInfo")).getJibunAddress() : "" );
      out.write("\">\n");
      out.write("\n");
      out.write("        <label>상세주소</label>\n");
      out.write("        <input type=\"text\" id=\"addrDetail\" name=\"addrDetail\">\n");
      out.write("\n");
      out.write("        <input type=\"hidden\" id=\"latitude\" name=\"latitude\">\n");
      out.write("        <input type=\"hidden\" id=\"longitude\" name=\"longitude\">\n");
      out.write("\n");
      out.write("        <label>모임 제목</label>\n");
      out.write("        <input type=\"text\" name=\"title\" required>\n");
      out.write("\n");
      out.write("        <label>내용</label>\n");
      out.write("        <textarea name=\"content\"></textarea>\n");
      out.write("\n");
      out.write("        <label>모임 날짜</label>\n");
      out.write("        ");

            String today = java.time.LocalDate.now().toString();
        
      out.write("\n");
      out.write("        <input type=\"date\" name=\"date\" value=\"");
      out.print( today );
      out.write("\" required>\n");
      out.write("\n");
      out.write("        <label>최대 인원</label>\n");
      out.write("        <input type=\"number\" name=\"maxMembers\" value=\"10\">\n");
      out.write("\n");
      out.write("        <label>현재 인원</label>\n");
      out.write("        <input type=\"number\" name=\"currentMembers\" value=\"1\">\n");
      out.write("\n");
      out.write("        <label>참가비</label>\n");
      out.write("        <input type=\"number\" name=\"cost\" value=\"0\">\n");
      out.write("\n");
      out.write("        <label>태그</label>\n");
      out.write("        <input type=\"text\" name=\"tag\">\n");
      out.write("\n");
      out.write("        <label>상태</label>\n");
      out.write("        <select name=\"status\">\n");
      out.write("            <option value=\"OPEN\">OPEN</option>\n");
      out.write("            <option value=\"CLOSED\">CLOSED</option>\n");
      out.write("            <option value=\"COMPLETED\">COMPLETED</option>\n");
      out.write("        </select>\n");
      out.write("\n");
      out.write("        <button type=\"submit\">생성하기</button>\n");
      out.write("    </form>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
