/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.49
 * Generated at: 2025-12-08 06:26:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.include;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import util.AuthUtil;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("util.AuthUtil");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- 헤더 CSS -->\n");
      out.write("<style>\n");
      out.write("    /* 헤더 전체 */\n");
      out.write("    header {\n");
      out.write("        display: flex;\n");
      out.write("        justify-content: space-between;\n");
      out.write("        align-items: flex-start;\n");
      out.write("        padding-top: 10px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .logo img {\n");
      out.write("        width: 100px !important;\n");
      out.write("        height: 100px !important;\n");
      out.write("        object-fit: contain;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .header-buttons {\n");
      out.write("        display: flex;\n");
      out.write("        gap: 10px;\n");
      out.write("        align-items: center;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    /* 메시지 버튼 */\n");
      out.write("    .msg-btn {\n");
      out.write("        background: #5271FF;\n");
      out.write("        color: white;\n");
      out.write("        padding: 8px 20px;\n");
      out.write("        border-radius: 10px;\n");
      out.write("        border: none;\n");
      out.write("        cursor: pointer;\n");
      out.write("        font-weight: 600;\n");
      out.write("        display: flex;\n");
      out.write("        align-items: center;\n");
      out.write("        gap: 6px;\n");
      out.write("        transition: 0.2s;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .msg-btn:hover {\n");
      out.write("        background: #3A50D8;\n");
      out.write("        transform: translateY(-2px);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    /* 마이페이지 버튼 */\n");
      out.write("    .mypage-btn {\n");
      out.write("        background: #FF6600;\n");
      out.write("        color: white;\n");
      out.write("        padding: 8px 20px;\n");
      out.write("        border-radius: 10px;\n");
      out.write("        border: none;\n");
      out.write("        cursor: pointer;\n");
      out.write("        font-weight: 600;\n");
      out.write("        display: flex;\n");
      out.write("        align-items: center;\n");
      out.write("        gap: 6px;\n");
      out.write("        transition: 0.2s;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .mypage-btn:hover {\n");
      out.write("        background: #e65c00;\n");
      out.write("        transform: translateY(-2px);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    /* 로그아웃/로그인 버튼 */\n");
      out.write("    .log-btn {\n");
      out.write("        background: #f0f0f0;\n");
      out.write("        color: #333;\n");
      out.write("        border: 1px solid #ccc;\n");
      out.write("        padding: 8px 20px;\n");
      out.write("        border-radius: 10px;\n");
      out.write("        cursor: pointer;\n");
      out.write("        font-weight: 600;\n");
      out.write("        display: flex;\n");
      out.write("        align-items: center;\n");
      out.write("        gap: 6px;\n");
      out.write("        transition: 0.2s;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .log-btn:hover {\n");
      out.write("        background: #e0e0e0;\n");
      out.write("    }\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<!-- 헤더 HTML -->\n");
      out.write("<header>\n");
      out.write("    <div class=\"logo\">\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/index.jsp\">\n");
      out.write("            <img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/images/logo.png\" alt=\"logo\">\n");
      out.write("        </a>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"header-buttons\">\n");
      out.write("        ");

            Object loginUser = session.getAttribute("Authorization");

            if (loginUser != null) {
                String token = (String) loginUser;
                String role = AuthUtil.getRole(request); // JWT에서 역할 추출
        
      out.write("\n");
      out.write("            <!-- 로그인 상태 공통: 메시지 버튼 -->\n");
      out.write("            <button class=\"msg-btn\"\n");
      out.write("                    onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/chat/roomList'\">\n");
      out.write("                메시지\n");
      out.write("            </button>\n");
      out.write("\n");
      out.write("            ");
 if ("ADMIN".equals(role)) { 
      out.write("\n");
      out.write("                <button class=\"log-btn\"\n");
      out.write("                        onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/admin'\">\n");
      out.write("                    관리자\n");
      out.write("                </button>\n");
      out.write("            ");
 } else { 
      out.write("\n");
      out.write("                <button class=\"mypage-btn\"\n");
      out.write("                        onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/views/user/mypage.jsp'\">\n");
      out.write("                    마이페이지\n");
      out.write("                </button>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("            <!-- 로그아웃 -->\n");
      out.write("            <form action=\"");
      out.print( request.getContextPath() );
      out.write("/user/logout\" method=\"get\" style=\"display:inline;\">\n");
      out.write("                <button type=\"submit\" class=\"log-btn\">Log out</button>\n");
      out.write("            </form>\n");
      out.write("\n");
      out.write("        ");
 } else { 
      out.write("\n");
      out.write("            <!-- 비로그인 상태 -->\n");
      out.write("            <button class=\"log-btn\"\n");
      out.write("                    onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/views/user/login.jsp'\">\n");
      out.write("                Log in\n");
      out.write("            </button>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("    </div>\n");
      out.write("</header>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
