/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.49
 * Generated at: 2025-12-08 06:26:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import dto.UserAddressDTO;
import util.AuthUtil;
import dto.UserAddressDTO;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("util.AuthUtil");
    _jspx_imports_classes.add("dto.UserAddressDTO");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>도란도란 - 우리 동네 유아·애견 커넥트</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"home.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div class=\"container\">\n");
      out.write("\n");
      out.write("    ");
      out.write("\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/include/header.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("    ");
      out.write("\n");
      out.write("    <section class=\"search-section\">\n");
      out.write("        <div class=\"search-row\">\n");
      out.write("            <select>\n");
      out.write("                <option>구로동</option>\n");
      out.write("                <option>가리봉동</option>\n");
      out.write("                <option>고척동</option>\n");
      out.write("            </select>\n");
      out.write("\n");
      out.write("            <select>\n");
      out.write("                <option>모임</option>\n");
      out.write("                <option>교환</option>\n");
      out.write("                <option>드림</option>\n");
      out.write("            </select>\n");
      out.write("\n");
      out.write("            <input type=\"text\" placeholder=\"검색어를 입력해주세요\">\n");
      out.write("            <button class=\"search-btn\">검색</button>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"title-main\">날씨가 쌀쌀하니 겉옷 꼭 챙기세요!</div>\n");
      out.write("        <div class=\"title-sub\">오늘의 추천활동은 실내 모임이에요 😊</div>\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("    ");
      out.write("\n");
      out.write("    <section class=\"main-box\">\n");
      out.write("        <div class=\"box-title\">우리 동네 기반 맞춤 추천</div>\n");
      out.write("\n");
      out.write("        <div class=\"grid-3\">\n");
      out.write("\n");
      out.write("            ");
      out.write("\n");
      out.write("            <div class=\"map-card\" id=\"map\" style=\"width:100%; height:400px;\"></div>\n");
      out.write("\n");
      out.write("            ");
 
            UserAddressDTO addressInfo = (UserAddressDTO) session.getAttribute("addressInfo");

            double defaultLat = 37.501;
            double defaultLng = 126.884;

            double lat = (addressInfo != null && addressInfo.getLatitude() != null)
                         ? addressInfo.getLatitude()
                         : defaultLat;

            double lng = (addressInfo != null && addressInfo.getLongitude() != null)
                         ? addressInfo.getLongitude()
                         : defaultLng;
            
      out.write("\n");
      out.write("\n");
      out.write("            <script>\n");
      out.write("                const userLat = ");
      out.print( lat );
      out.write(";\n");
      out.write("                const userLng = ");
      out.print( lng );
      out.write(";\n");
      out.write("            </script>\n");
      out.write("            <script src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=ef8233e9a835b606aa5918095ec92f2b&libraries=services\"></script>\n");
      out.write("            <script>\n");
      out.write("                window.onload = function() {\n");
      out.write("                    if (!window.kakao) {\n");
      out.write("                        alert(\"카카오 지도 SDK 로드 실패\");\n");
      out.write("                        return;\n");
      out.write("                    }\n");
      out.write("\n");
      out.write("                    var container = document.getElementById('map');\n");
      out.write("                    var options = {\n");
      out.write("                        center: new kakao.maps.LatLng(userLat, userLng),\n");
      out.write("                        level: 3\n");
      out.write("                    };\n");
      out.write("\n");
      out.write("                    var map = new kakao.maps.Map(container, options);\n");
      out.write("\n");
      out.write("                    var markerPosition  = new kakao.maps.LatLng(userLat, userLng);\n");
      out.write("                    var marker = new kakao.maps.Marker({ position: markerPosition });\n");
      out.write("                    marker.setMap(map);\n");
      out.write("\n");
      out.write("                    console.log(\"카카오 지도 로드 완료\");\n");
      out.write("                }\n");
      out.write("            </script>\n");
      out.write("\n");
      out.write("            ");
      out.write("\n");
      out.write("            <div class=\"center-card\">\n");
      out.write("                <div class=\"center-title\">오늘의 인기 모임 🔥</div>\n");
      out.write("                <div class=\"center-desc\">지금 우리 동네에서 가장 활발한 모임을 소개해드릴게요!</div>\n");
      out.write("\n");
      out.write("                <div class=\"popular-grid\">\n");
      out.write("\n");
      out.write("                    <div class=\"popular-card\">\n");
      out.write("                        <img src=\"resources/images/kidsPlay.jpg\" alt=\"pop1\">\n");
      out.write("                        <div class=\"pop-info\">\n");
      out.write("                            <h3>주말 실내 키즈 플레이라운지</h3>\n");
      out.write("                            <p>구로 · 5명 참여중</p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"popular-card\">\n");
      out.write("                        <img src=\"resources/images/dogWalking.jpg\" alt=\"pop2\">\n");
      out.write("                        <div class=\"pop-info\">\n");
      out.write("                            <h3>강아지 소형견 산책 모임</h3>\n");
      out.write("                            <p>고척 · 3명 참여중</p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"popular-card\">\n");
      out.write("                        <img src=\"resources/images/baby.jpg\" alt=\"pop3\">\n");
      out.write("                        <div class=\"pop-info\">\n");
      out.write("                            <h3>첫 육아 부모 대화방</h3>\n");
      out.write("                            <p>가리봉 · 12명 활성</p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"popular-card\">\n");
      out.write("                        <img src=\"resources/images/doggroup.jpg\" alt=\"pop4\">\n");
      out.write("                        <div class=\"pop-info\">\n");
      out.write("                            <h3>초보 펫돌보미 공유 모임</h3>\n");
      out.write("                            <p>구로 · 7명 참여중</p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            ");
      out.write("\n");
      out.write("            <div>\n");
      out.write("                <div class=\"weather-card\">\n");
      out.write("                    <div class=\"weather-title\">현재 구로동 날씨</div>\n");
      out.write("                    <div class=\"weather-temp\">14.5°C</div>\n");
      out.write("                    <div class=\"weather-status\">맑음 • 미세먼지 좋음</div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"activities\">\n");
      out.write("\n");
      out.write("                    ");
      out.write("\n");
      out.write("                    <a href=\"");
      out.print( request.getContextPath() );
      out.write("/meeting/list\" class=\"activity-card\" style=\"text-decoration:none; color:inherit;\">\n");
      out.write("                        <img src=\"resources/images/meeting.jpg\" alt=\"meet\">\n");
      out.write("                        <span>모임</span>\n");
      out.write("                    </a>\n");
      out.write("\n");
      out.write("                    <div class=\"activity-card\">\n");
      out.write("                        <img src=\"resources/images/trade.jpg\" alt=\"friend\">\n");
      out.write("                        <span>교환</span>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"activity-card\">\n");
      out.write("                        <img src=\"resources/images/giving.jpg\" alt=\"chat\">\n");
      out.write("                        <span>드림</span>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
