/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.49
 * Generated at: 2025-12-08 06:27:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.user;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>로그인</title>\n");
      out.write("<style>\n");
      out.write("    @charset \"UTF-8\";\n");
      out.write("\n");
      out.write("    /* ==================== 전체 스타일 ==================== */\n");
      out.write("    body {\n");
      out.write("        margin: 0;\n");
      out.write("        padding: 0;\n");
      out.write("        background: #F5F6FA;\n");
      out.write("        font-family: 'Pretendard', sans-serif;\n");
      out.write("        color: #222;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    /* 컨테이너 중앙 정렬 */\n");
      out.write("    .container {\n");
      out.write("        width: 360px;\n");
      out.write("        max-width: 90%;\n");
      out.write("        margin: 80px auto;\n");
      out.write("        background: #fff;\n");
      out.write("        padding: 40px;\n");
      out.write("        border-radius: 20px;\n");
      out.write("        box-shadow: 0 6px 24px rgba(0,0,0,0.06);\n");
      out.write("        display: flex;\n");
      out.write("        flex-direction: column;\n");
      out.write("        align-items: center;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    /* 제목 중앙 정렬 */\n");
      out.write("    h2 {\n");
      out.write("        text-align: center;\n");
      out.write("        font-size: 28px;\n");
      out.write("        font-weight: 700;\n");
      out.write("        color: #FF7C40;\n");
      out.write("        margin-bottom: 30px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    /* 폼 전체 */\n");
      out.write("    form {\n");
      out.write("        width: 100%;\n");
      out.write("        display: flex;\n");
      out.write("        flex-direction: column;\n");
      out.write("        gap: 20px; /* 레이블과 입력 필드 간격 */\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    label {\n");
      out.write("        font-weight: 600;\n");
      out.write("        color: #555;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    input[type=\"text\"], input[type=\"password\"], button {\n");
      out.write("        width: 100%;\n");
      out.write("        box-sizing: border-box; /* padding 포함 너비 계산 */\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    input[type=\"text\"], input[type=\"password\"] {\n");
      out.write("        padding: 12px 16px;\n");
      out.write("        border-radius: 12px;\n");
      out.write("        border: 1px solid #DDD;\n");
      out.write("        font-size: 15px;\n");
      out.write("        outline: none;\n");
      out.write("        transition: 0.15s;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    input[type=\"text\"]:focus, input[type=\"password\"]:focus {\n");
      out.write("        border-color: #FF7C40;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    button {\n");
      out.write("        padding: 12px;\n");
      out.write("        border: none;\n");
      out.write("        border-radius: 12px;\n");
      out.write("        background: #FF7C40;\n");
      out.write("        color: white;\n");
      out.write("        font-size: 16px;\n");
      out.write("        font-weight: 700;\n");
      out.write("        cursor: pointer;\n");
      out.write("        transition: 0.15s;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    button:hover {\n");
      out.write("        background: #ff6720;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    /* 회원가입 링크 */\n");
      out.write("    p {\n");
      out.write("        text-align: center;\n");
      out.write("        margin-top: 20px;\n");
      out.write("        font-size: 14px;\n");
      out.write("        color: #666;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    a {\n");
      out.write("        color: #5271FF;\n");
      out.write("        font-weight: 600;\n");
      out.write("        text-decoration: none;\n");
      out.write("        transition: 0.15s;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    a:hover {\n");
      out.write("        text-decoration: underline;\n");
      out.write("    }\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
 
    String errorMsg = (String) request.getAttribute("errorMsg");
    if (errorMsg != null) { 

      out.write("\n");
      out.write("    <script>\n");
      out.write("        alert(\"");
      out.print( errorMsg );
      out.write("\");\n");
      out.write("    </script>\n");

    }

      out.write("\n");
      out.write("\n");
      out.write("<div class=\"container\">\n");
      out.write("    <h2>로그인</h2>\n");
      out.write("    <form action=\"");
      out.print( request.getContextPath() );
      out.write("/user/login\" method=\"post\">\n");
      out.write("        <div>\n");
      out.write("            <label>아이디</label>\n");
      out.write("            <input type=\"text\" name=\"userId\" placeholder=\"아이디를 입력하세요\" required>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div>\n");
      out.write("            <label>비밀번호</label>\n");
      out.write("            <input type=\"password\" name=\"userPassword\" placeholder=\"비밀번호를 입력하세요\" required>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <button type=\"submit\">로그인</button>\n");
      out.write("    </form>\n");
      out.write("\n");
      out.write("    <p>회원이 아니신가요? <a href=\"register.jsp\">회원가입</a></p>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
