/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.49
 * Generated at: 2025-12-08 06:43:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.user;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import dto.UserDTO;
import dto.UserAddressDTO;

public final class mypage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("dto.UserDTO");
    _jspx_imports_classes.add("dto.UserAddressDTO");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>마이페이지 - 도란도란</title>\n");
      out.write("	<style>\n");
      out.write("        body { margin:0; padding:0; background:#F5F6FA; font-family:'Pretendard',sans-serif; color:#222; }\n");
      out.write("        .container { width:1400px; margin:0 auto; padding:20px 40px; }\n");
      out.write("        header { display:flex; justify-content:space-between; align-items:flex-start; padding-top:10px; }\n");
      out.write("        .logo { display:flex; align-items:center; gap:10px; font-size:28px; font-weight:800; color:#FF7C40; }\n");
      out.write("        .logo img { width:100px; height:100px; object-fit:contain; }\n");
      out.write("        .header-buttons { display:flex; gap:10px; align-items:center; }\n");
      out.write("        .log-btn, .mypage-btn, .update-btn, .delete-btn {\n");
      out.write("            padding:8px 20px; border-radius:10px; border:none; cursor:pointer; font-weight:600;\n");
      out.write("            display:flex; align-items:center; gap:6px; transition:0.2s;\n");
      out.write("        }\n");
      out.write("        .log-btn { background:#f0f0f0; color:#333; border:1px solid #ccc; }\n");
      out.write("        .log-btn:hover { background:#e0e0e0; }\n");
      out.write("        .mypage-btn, .update-btn { background:#FF6600; color:white; }\n");
      out.write("        .mypage-btn:hover, .update-btn:hover { background:#e65c00; }\n");
      out.write("        .delete-btn { background:#FF4444; color:white; }\n");
      out.write("        .delete-btn:hover { background:#cc3333; }\n");
      out.write("\n");
      out.write("        .main-box { margin-top:50px; background:white; padding:45px; border-radius:24px; box-shadow:0 6px 24px rgba(0,0,0,0.06); }\n");
      out.write("        .box-title { font-size:22px; font-weight:700; margin-bottom:25px; }\n");
      out.write("        .grid-3 { display:grid; grid-template-columns:1.2fr 1.8fr 1fr; gap:32px; }\n");
      out.write("\n");
      out.write("        .center-card, .map-card, .weather-card {\n");
      out.write("            background:#FCFBFE; border-radius:20px; padding:30px; box-shadow:0 4px 16px rgba(0,0,0,0.05);\n");
      out.write("        }\n");
      out.write("        .center-title { font-size:20px; font-weight:700; margin-bottom:12px; }\n");
      out.write("        .center-desc { color:#666; font-size:16px; margin-bottom:20px; }\n");
      out.write("\n");
      out.write("        input[type=\"text\"], input[type=\"password\"] {\n");
      out.write("            width:100%; padding:12px 15px; margin:5px 0 15px 0; border-radius:12px; border:1px solid #DDD; font-size:15px; font-weight:500;\n");
      out.write("        }\n");
      out.write("        label { font-weight:600; font-size:14px; }\n");
      out.write("\n");
      out.write("        /* ================= 프로필 이미지 영역 ================= */\n");
      out.write("        .profile-box {\n");
      out.write("            width: 150px; height:150px; margin-bottom:15px; border-radius:50%; overflow:hidden; border:2px solid #aaa;\n");
      out.write("        }\n");
      out.write("        .profile-box img { width:100%; height:100%; object-fit:cover; }\n");
      out.write("\n");
      out.write("        .profile-actions { display:flex; gap:10px; margin-bottom:15px; }\n");
      out.write("        .profile-actions button { flex:1; padding:8px 10px; border-radius:8px; border:none; cursor:pointer; font-weight:600; }\n");
      out.write("        .upload-btn { background:#FF6600; color:white; }\n");
      out.write("        .delete-btn-small { background:#FF4444; color:white; }\n");
      out.write("    </style>\n");
      out.write("    <script>\n");
      out.write("		const POPUP_KEY = \"");
      out.print( "devU01TX0FVVEgyMDI1MTEyNDEwMTMwNjExNjQ4NTc=" );
      out.write("\"; // 팝업용 키\n");
      out.write("		const RETURN_URL = \"http://localhost:8080");
      out.print( request.getContextPath() );
      out.write("/views/util/addressPopupReturn.jsp\";\n");
      out.write("		function openJusoPopup() {\n");
      out.write("		    window.open(\n");
      out.write("		        \"https://business.juso.go.kr/addrlink/addrLinkUrl.do?confmKey=\" + POPUP_KEY \n");
      out.write("		        + \"&returnUrl=\" + encodeURIComponent(RETURN_URL)\n");
      out.write("		        + \"&resultType=4\",\n");
      out.write("		        \"jusoPopup\",\n");
      out.write("		        \"width=570,height=420,scrollbars=yes,resizable=yes\"\n");
      out.write("		    );\n");
      out.write("		}\n");
      out.write("	</script>\n");
      out.write("	<script src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=ef8233e9a835b606aa5918095ec92f2b&libraries=services\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div class=\"container\">\n");
      out.write("\n");
      out.write("\n");
      out.write(" 	    ");
      out.write("\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/include/header.jsp", out, false);
      out.write('\n');
      out.write('\n');
      out.write('\n');

    UserDTO user = (UserDTO) session.getAttribute("userInfo");
    UserAddressDTO addr = (UserAddressDTO) session.getAttribute("addressInfo");
    
    if (user != null) {

      out.write('\n');

    // 프로필 이미지 URL 세션에서 가져오기
    String profileUrl = (String) session.getAttribute("profileUrl");
    if(profileUrl == null || profileUrl.isEmpty()) {
        profileUrl = "/resources/images/default_profile.png"; // 기본 이미지 경로
    }

      out.write("\n");
      out.write("\n");
      out.write("<section class=\"main-box\">\n");
      out.write("    <div class=\"box-title\">마이페이지</div>\n");
      out.write("    <div class=\"grid-3\">\n");
      out.write("\n");
      out.write("        ");
      out.write("\n");
      out.write("        <div class=\"center-card\">\n");
      out.write("            <div class=\"center-title\">내 정보</div>\n");
      out.write("            <div class=\"center-desc\">회원님의 정보를 확인하고 수정할 수 있습니다.</div>\n");
      out.write("\n");
      out.write("            <!-- 프로필 이미지 -->\n");
      out.write("            <div class=\"profile-box\">\n");
      out.write("                <img src=\"");
      out.print( request.getContextPath() + profileUrl );
      out.write("\" alt=\"프로필 이미지\">\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!-- 이미지 업로드 / 삭제 -->\n");
      out.write("            <div class=\"profile-actions\">\n");
      out.write("			<form id=\"profileForm\" action=\"");
      out.print( request.getContextPath() );
      out.write("/upload/profileUpload\" method=\"post\" enctype=\"multipart/form-data\">\n");
      out.write("			    <!-- 실제 파일 input은 숨김 -->\n");
      out.write("			    <input type=\"file\" id=\"profileInput\" name=\"img\" accept=\"image/*\" style=\"display:none;\" required>\n");
      out.write("			    \n");
      out.write("			    <!-- 사용자가 누를 버튼 -->\n");
      out.write("			    <button type=\"button\" id=\"uploadBtn\">이미지 등록/수정</button>\n");
      out.write("			</form>\n");
      out.write("			\n");
      out.write("			<form id=\"profileDeleteForm\"\n");
      out.write("			      action=\"");
      out.print( request.getContextPath() );
      out.write("/upload/profileDelete\"\n");
      out.write("			      method=\"post\">\n");
      out.write("			\n");
      out.write("			    <button type=\"submit\"\n");
      out.write("			            style=\"background:#ff4e4e; color:white;\">\n");
      out.write("			        프로필 이미지 삭제\n");
      out.write("			    </button>\n");
      out.write("			</form>\n");
      out.write("			\n");
      out.write("			\n");
      out.write("			<script>\n");
      out.write("			    const uploadBtn = document.getElementById('uploadBtn');\n");
      out.write("			    const fileInput = document.getElementById('profileInput');\n");
      out.write("			    const form = document.getElementById('profileForm');\n");
      out.write("			\n");
      out.write("			    // 버튼 클릭 시 파일 선택 창 열기\n");
      out.write("			    uploadBtn.addEventListener('click', () => fileInput.click());\n");
      out.write("			\n");
      out.write("			    // 파일 선택 후 자동 제출\n");
      out.write("			    fileInput.addEventListener('change', () => form.submit());\n");
      out.write("			</script>\n");
      out.write("            </div> \n");
      out.write("		\n");
      out.write("		    ");
      out.write("\n");
      out.write("		    <form id=\"updateForm\" action=\"");
      out.print( request.getContextPath() );
      out.write("/user/update\" method=\"post\">\n");
      out.write("		        <input type=\"hidden\" name=\"autoId\" value=\"");
      out.print( user.getAutoId() );
      out.write("\">\n");
      out.write("		\n");
      out.write("		        <label>이름</label>\n");
      out.write("		        <input type=\"text\" value=\"");
      out.print( user.getUserName() != null ? user.getUserName() : "" );
      out.write("\" disabled>\n");
      out.write("		\n");
      out.write("		        <label>닉네임</label>\n");
      out.write("		        <input type=\"text\" name=\"newNickname\" value=\"");
      out.print( user.getNickname() != null ? user.getNickname() : "" );
      out.write("\">\n");
      out.write("		\n");
      out.write("		        <label>비밀번호</label>\n");
      out.write("		        <input type=\"password\" name=\"newPassword\" placeholder=\"변경할 비밀번호\">\n");
      out.write("		\n");
      out.write("		                        ");
      out.write("\n");
      out.write("                <label>주소</label>\n");
      out.write("                <button type=\"button\" class=\"update-btn\" onclick=\"openJusoPopup()\" style=\"width:auto; margin-bottom:10px;\">주소 검색</button>\n");
      out.write("\n");
      out.write("				<!-- 도로명주소 -->\n");
      out.write("				<label>도로명주소</label>\n");
      out.write("				<input type=\"text\" id=\"roadAddress\" disabled value=\"");
      out.print( (addr != null && addr.getRoadAddress() != null) ? addr.getRoadAddress() : "" );
      out.write("\" />\n");
      out.write("				\n");
      out.write("				<input type=\"hidden\" id=\"roadAddressValue\" name=\"roadAddress\" value=\"");
      out.print( (addr != null && addr.getRoadAddress() != null) ? addr.getRoadAddress() : "" );
      out.write("\" />\n");
      out.write("				\n");
      out.write("				\n");
      out.write("				<!-- 지번주소 disabled라 팝업에서 .textContent가 아니라 .value 사용해야함-->\n");
      out.write("				<label>지번주소</label>\n");
      out.write("				<input type=\"text\" id=\"jibunAddress\" disabled value=\"");
      out.print( (addr != null && addr.getJibunAddress() != null) ? addr.getJibunAddress() : "" );
      out.write("\" />\n");
      out.write("				\n");
      out.write("				<input type=\"hidden\" id=\"jibunAddressValue\" name=\"jibunAddress\" value=\"");
      out.print( (addr != null && addr.getJibunAddress() != null) ? addr.getJibunAddress() : "" );
      out.write("\" />\n");
      out.write("				\n");
      out.write("				<!-- 상세주소 (유저 입력 가능) -->	\n");
      out.write("				<label>상세주소</label>\n");
      out.write("				<input type=\"text\" id=\"addrDetail\" value=\"");
      out.print( (addr != null && addr.getAddrDetail() != null) ? addr.getAddrDetail() : "" );
      out.write("\" />\n");
      out.write("\n");
      out.write("				<input type=\"hidden\" id=\"addrDetailValue\" name=\"addrDetail\" value=\"");
      out.print( (addr != null && addr.getAddrDetail() != null) ? addr.getAddrDetail() : "" );
      out.write("\" />\n");
      out.write("				\n");
      out.write("				<input type=\"hidden\" id=\"latitude\" name=\"latitude\">\n");
      out.write("				<input type=\"hidden\" id=\"longitude\" name=\"longitude\">\n");
      out.write("				\n");
      out.write("		        <button type=\"submit\" class=\"update-btn\">정보 수정</button>\n");
      out.write("		    </form>\n");
      out.write("		\n");
      out.write("		    <form action=\"");
      out.print( request.getContextPath() );
      out.write("/user/delete\" method=\"post\" onsubmit=\"return confirm('정말 탈퇴하시겠습니까?');\">\n");
      out.write("		        <input type=\"hidden\" name=\"autoId\" value=\"");
      out.print( user.getAutoId() );
      out.write("\">\n");
      out.write("		        <button type=\"submit\" class=\"delete-btn\">회원 탈퇴</button>\n");
      out.write("		    </form>\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("        ");
      out.write("\n");
      out.write("        <div class=\"map-card\" style=\"display:flex; justify-content:center; align-items:center; color:#666;\">\n");
      out.write("            추가 통계 또는 최근 활동 영역\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        ");
      out.write("\n");
      out.write("        <div class=\"weather-card\" style=\"display:flex; justify-content:center; align-items:center; color:#666;\">\n");
      out.write("            알림 및 추천 활동 영역\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("\n");
 } else { 
      out.write("\n");
      out.write("<div class=\"main-box\" style=\"text-align:center;\">\n");
      out.write("    <p>로그인이 필요합니다. <a href=\"");
      out.print( request.getContextPath() );
      out.write("/views/user/login.jsp\">로그인 페이지로 이동</a></p>\n");
      out.write("</div>\n");
 } 
      out.write("\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("<script>\n");
      out.write("    // 카카오 Geocoder 객체 생성\n");
      out.write("    var geocoder = new kakao.maps.services.Geocoder();\n");
      out.write("\n");
      out.write("    // form submit 가로채기\n");
      out.write("    document.addEventListener(\"DOMContentLoaded\", function () {\n");
      out.write("        document.getElementById(\"updateForm\").addEventListener(\"submit\", function(e) {\n");
      out.write("            e.preventDefault();\n");
      out.write("\n");
      out.write("            let roadAddr = document.getElementById(\"roadAddressValue\").value;\n");
      out.write("            let jibunAddr = document.getElementById(\"jibunAddressValue\").value;\n");
      out.write("\n");
      out.write("            let finalAddress = roadAddr || jibunAddr;\n");
      out.write("\n");
      out.write("            if (!finalAddress) {\n");
      out.write("                alert(\"주소가 없습니다. 주소 검색을 먼저 해주세요.\");\n");
      out.write("                return;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            // 주소 → 좌표 변환\n");
      out.write("            geocoder.addressSearch(finalAddress, function(result, status) {\n");
      out.write("                if (status === kakao.maps.services.Status.OK) {\n");
      out.write("\n");
      out.write("                    let lat = result[0].y;\n");
      out.write("                    let lng = result[0].x;\n");
      out.write("\n");
      out.write("                    document.getElementById(\"latitude\").value = lat;\n");
      out.write("                    document.getElementById(\"longitude\").value = lng;\n");
      out.write("\n");
      out.write("                    console.log(\"위도:\", lat, \"경도:\", lng);\n");
      out.write("\n");
      out.write("                    // 실제 제출\n");
      out.write("                    e.target.submit();\n");
      out.write("\n");
      out.write("                } else {\n");
      out.write("                    alert(\"주소 → 좌표 변환 실패: \" + status);\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("        });\n");
      out.write("    });\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
