/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.49
 * Generated at: 2025-12-10 05:08:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class adminMain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1764140562289L));
    _jspx_dependants.put("jar:file:/C:/Users/CMS/Desktop/백앤드%20프로젝트/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/gimalProject/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602841572000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>관리자 메인</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/admin.css\">\n");
      out.write("</head>\n");
      out.write("<body class=\"admin-body\">\n");
      out.write("\n");
      out.write("<div class=\"admin-container\">\n");
      out.write("\n");
      out.write("    <!-- 상단 헤더 -->\n");
      out.write("    <header>\n");
      out.write("        <h1>관리자 메인</h1>\n");
      out.write("\n");
      out.write("        <div class=\"header-buttons\">\n");
      out.write("            <button class=\"log-btn\"\n");
      out.write("                    onclick=\"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/'\">\n");
      out.write("                홈으로\n");
      out.write("            </button>\n");
      out.write("        </div>\n");
      out.write("    </header>\n");
      out.write("\n");
      out.write("    <!-- 안내 텍스트 + 카드들 -->\n");
      out.write("    <div class=\"main-box\">\n");
      out.write("        <div class=\"box-title\">관리 기능 한눈에 보기</div>\n");
      out.write("        <p>도란도란 모임 서비스를 안전하고 효율적으로 운영하기 위한 관리자 전용 메뉴입니다.</p>\n");
      out.write("\n");
      out.write("        <div class=\"admin-card-grid\">\n");
      out.write("\n");
      out.write("            <!-- 공지 관리 카드 -->\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/notice/list\" class=\"admin-card\">\n");
      out.write("                <div class=\"admin-card-header\">\n");
      out.write("                    <div>\n");
      out.write("                        <div class=\"admin-card-title\">공지 관리</div>\n");
      out.write("                        <div class=\"admin-card-sub\">\n");
      out.write("                            모임 운영 관련 공지를 등록·수정·삭제할 수 있어요.\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"admin-card-icon\">🔔</div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <ul class=\"admin-card-meta-list\">\n");
      out.write("                    <li>중요 공지나 서비스 점검 일정 등록</li>\n");
      out.write("                    <li>기간 지난 공지 정리하여 서비스 운영 최적화</li>\n");
      out.write("                </ul>\n");
      out.write("            </a>\n");
      out.write("\n");
      out.write("            <!-- 회원 관리 카드 -->\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/users\" class=\"admin-card\">\n");
      out.write("                <div class=\"admin-card-header\">\n");
      out.write("                    <div>\n");
      out.write("                        <div class=\"admin-card-title\">회원 관리</div>\n");
      out.write("                        <div class=\"admin-card-sub\">\n");
      out.write("                            회원 정보를 조회하고, 정지·탈퇴 처리가 가능해요.\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"admin-card-icon\">👤</div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <ul class=\"admin-card-meta-list\">\n");
      out.write("                    <li>문제가 되는 회원 차단 (BLOCKED)</li>\n");
      out.write("                    <li>회원 상세 정보와 활동 내역 확인</li>\n");
      out.write("                </ul>\n");
      out.write("            </a>\n");
      out.write("\n");
      out.write("            <!-- 신고 관리 카드 -->\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/reports\" class=\"admin-card\">\n");
      out.write("                <div class=\"admin-card-header\">\n");
      out.write("                    <div>\n");
      out.write("                        <div class=\"admin-card-title\">신고 관리</div>\n");
      out.write("                        <div class=\"admin-card-sub\">\n");
      out.write("                            회원 신고를 확인하고 처리할 수 있어요.\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"admin-card-icon\">⚠️</div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <ul class=\"admin-card-meta-list\">\n");
      out.write("                    <li>대기 → 정지 처리 가능</li>\n");
      out.write("                    <li>신고 내용 검토 후 제재 여부 결정</li>\n");
      out.write("                </ul>\n");
      out.write("            </a>\n");
      out.write("\n");
      out.write("            <!-- ✅ 모임 관리 카드 (새로 추가된 부분) -->\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/meeting/list\" class=\"admin-card\">\n");
      out.write("                <div class=\"admin-card-header\">\n");
      out.write("                    <div>\n");
      out.write("                        <div class=\"admin-card-title\">모임 관리</div>\n");
      out.write("                        <div class=\"admin-card-sub\">\n");
      out.write("                            개설된 모임을 한눈에 보고 상태 변경·삭제를 할 수 있어요.\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"admin-card-icon\">📅</div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <ul class=\"admin-card-meta-list\">\n");
      out.write("                    <li>전체 모임 목록 확인</li>\n");
      out.write("                    <li>문제 있는 모임 상태 변경 또는 삭제</li>\n");
      out.write("                </ul>\n");
      out.write("            </a>\n");
      out.write("\n");
      out.write("            <!-- 서비스 통계 카드 -->\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/stats\" class=\"admin-card\">\n");
      out.write("                <div class=\"admin-card-header\">\n");
      out.write("                    <div>\n");
      out.write("                        <div class=\"admin-card-title\">서비스 통계</div>\n");
      out.write("                        <div class=\"admin-card-sub\">\n");
      out.write("                            회원 증가, 모임 개설 수, 신고 현황을 그래프로 확인할 수 있어요.\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"admin-card-icon\">📊</div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <ul class=\"admin-card-meta-list\">\n");
      out.write("                    <li>모임 서비스 운영 상태 한눈에 파악</li>\n");
      out.write("                    <li>신고 현황과 회원 활동 분석</li>\n");
      out.write("                </ul>\n");
      out.write("            </a>\n");
      out.write("\n");
      out.write("        </div><!-- /.admin-card-grid -->\n");
      out.write("    </div><!-- /.main-box -->\n");
      out.write("\n");
      out.write("</div><!-- /.admin-container -->\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
